
-define(S2CELLUNIONCONSTRUCTORS_INIT_FROM_CELLIDS,   1).
-define(S2CELLUNIONCONSTRUCTORS_INIT_FROM_UINT64,    2).
-define(S2CELLUNIONCONSTRUCTORS_DECODE,              3).
-define(S2CELLUNIONCONSTRUCTORS_INIT_FROM_RANGE,     4).


-define(S2CELLUNIONMETHODS_NUM_CELLS,           10).
-define(S2CELLUNIONMETHODS_CELL_ID,             11).
-define(S2CELLUNIONMETHODS_CELL_IDS,            12).
-define(S2CELLUNIONMETHODS_NORMALIZE,           13).

-define(S2CELLUNIONMETHODS_CONTAINS_S2CELLID,             20).
-define(S2CELLUNIONMETHODS_INTERSECTS_S2CELLID,           21).
-define(S2CELLUNIONMETHODS_CONTAINS_S2CELLUNION,          22).
-define(S2CELLUNIONMETHODS_INTERSECTS_S2CELLUNION,        23).
-define(S2CELLUNIONMETHODS_GET_UNION,                     24).
-define(S2CELLUNIONMETHODS_GET_INTERSECTION,              25).
-define(S2CELLUNIONMETHODS_GET_DIFFERENCE,                26).
-define(S2CELLUNIONMETHODS_GET_INTERSECTION_WITH_S2CELLID,  27).

-define(S2CELLUNIONMETHODS_EXPAND_LEVEL,                  28).
-define(S2CELLUNIONMETHODS_EXPAND_RADIUS,                 29).

-define(S2CELLUNIONMETHODS_LEAF_CELLS_COVERED,            40).
-define(S2CELLUNIONMETHODS_AVERAGE_BASED_AREA,            41).
-define(S2CELLUNIONMETHODS_APPROX_AREA,                   42).
-define(S2CELLUNIONMETHODS_EXACT_AREA,                    43).
-define(S2CELLUNIONMETHODS_GET_RECT_BOUND,                44).
-define(S2CELLUNIONMETHODS_CONTAINS_S2CELL,               45).
-define(S2CELLUNIONMETHODS_MAY_INTERSECT_S2CELL,          46).
-define(S2CELLUNIONMETHODS_CONTAINS_S2POINT,              47).

-define(S2CELLUNIONMETHODS_ENCODE,                        50).
