-define(REGION_COVERER_DEFAULTMAXCELLS, 8).

-define(S2REGIONCOVERINGTYPE_CELLID_COVERING,                  1).
-define(S2REGIONCOVERINGTYPE_CELLID_INTERIOR_COVERING,         2).
-define(S2REGIONCOVERINGTYPE_CELL_UNION_COVERING,              3).
-define(S2REGIONCOVERINGTYPE_INTERIOR_CELL_UNION_COVERING,     4).
