
-define(S2LATLNGRECT_FROM_LAT_LNG_DEGREE,    1).
-define(S2LATLNGRECT_FROM_LAT_LNG,           2).
-define(S2LATLNGRECT_EMPTY,                  3).
-define(S2LATLNGRECT_FULL,                   4).
-define(S2LATLNGRECT_FROM_CENTER_SIZE,       5).
-define(S2LATLNGRECT_FROM_POINT,             6).
-define(S2LATLNGRECT_FROM_POINT_PAIR,        7).
-define(S2LATLNGRECT_DECODE,                 10).

-define(S2LATLNGRECT_METHOD_LAT_LO,       101).
-define(S2LATLNGRECT_METHOD_LAT_HI,       102).
-define(S2LATLNGRECT_METHOD_LNG_LO,       103).
-define(S2LATLNGRECT_METHOD_LNG_HI,       104).
-define(S2LATLNGRECT_METHOD_LAT,          105).
-define(S2LATLNGRECT_METHOD_LNG,          106).
-define(S2LATLNGRECT_METHOD_LO,           107).
-define(S2LATLNGRECT_METHOD_HI,           108).

-define(S2LATLNGRECT_METHOD_IS_VALID,     110).
-define(S2LATLNGRECT_METHOD_IS_EMPTY,     111).
-define(S2LATLNGRECT_METHOD_IS_FULL,      112).
-define(S2LATLNGRECT_METHOD_IS_POINT,     113).
-define(S2LATLNGRECT_METHOD_IS_INVERTED,  114).

-define(S2LATLNGRECT_METHOD_GET_VERTEX,   120).
-define(S2LATLNGRECT_METHOD_GET_CENTER,   121).
-define(S2LATLNGRECT_METHOD_GET_SIZE,     122).
-define(S2LATLNGRECT_METHOD_AREA,         123).

-define(S2LATLNGRECT_METHOD_CONTAINS_S2LATLNG,              130).
-define(S2LATLNGRECT_METHOD_INTERIOR_CONTAINS_S2POINT,      131).
-define(S2LATLNGRECT_METHOD_INTERIOR_CONTAINS_S2LATLNG,     132).
-define(S2LATLNGRECT_METHOD_CONTAINS_S2LATLNGRECT,          133).
-define(S2LATLNGRECT_METHOD_INTERIOR_CONTAINS_S2LATLNGRECT,   134).
-define(S2LATLNGRECT_METHOD_INTERSECTS_S2LATLNGRECT,        135).
-define(S2LATLNGRECT_METHOD_INTERSECTS_S2CELL_WITH_ID,      136).
-define(S2LATLNGRECT_METHOD_INTERIOR_INTERSECTS_S2LATLNGRECT,   137).

-define(S2LATLNGRECT_METHOD_CONTAINS_S2CELL_WITH_ID,  138).
-define(S2LATLNGRECT_METHOD_CONTAINS_S2POINT,  139).
-define(S2LATLNGRECT_METHOD_MAY_INTERSECT_S2CELL_WITH_ID,  140).

-define(S2LATLNGRECT_METHOD_EXPANDED,             142).
-define(S2LATLNGRECT_METHOD_UNION,                143).
-define(S2LATLNGRECT_METHOD_INTERSECTION,         144).
-define(S2LATLNGRECT_METHOD_CONVOLVE_WITH_CAP,    145).

-define(S2LATLNGRECT_METHOD_ADD_POINT_S2LATLNG,   146).
-define(S2LATLNGRECT_METHOD_ADD_POINT,            147).

-define(S2LATLNGRECT_METHOD_GET_DISTANCE,               150).
-define(S2LATLNGRECT_METHOD_GET_DISTANCE_S2LATLNG,      151).
-define(S2LATLNGRECT_METHOD_GET_DIRECTED_HAUSDORFF_DISTANCE,  152).
-define(S2LATLNGRECT_METHOD_GET_HAUSDORFF_DISTANCE,     153).

-define(S2LATLNGRECT_METHOD_EQUAL,  160).
-define(S2LATLNGRECT_METHOD_NOT_EQUAL,  161).
-define(S2LATLNGRECT_METHOD_APPROX_EQUALS,  162).

-define(S2LATLNGRECT_METHOD_GET_CAP_BOUND,  170).
-define(S2LATLNGRECT_METHOD_GET_RECT_BOUND,  171).
-define(S2LATLNGRECT_METHOD_ENCODE,  180).

