
-define(S2LATLNGRECT_CONSTRUCTOR_FROM_LAT_LNG_DEGREE, 1).
-define(S2LATLNGRECT_CONSTRUCTOR_FROM_LAT_LNG,        2).
-define(S2LATLNGRECT_CONSTRUCTOR_EMPTY,               3).
-define(S2LATLNGRECT_CONSTRUCTOR_FROM_CENTER_SIZE,    4).
