
-define(S2LOOPCONSTRUCTORS_FROM_S2POINT_LIST,    1).
-define(S2LOOPCONSTRUCTORS_FROM_S2LATLNG_LIST,   2).
-define(S2LOOPCONSTRUCTORS_FROM_S2CELLID,        3).
-define(S2LOOPCONSTRUCTORS_DECODE,               4).
-define(S2LOOPCONSTRUCTORS_INVERT,               5).

-define(S2LOOPMETHODS_IS_VALID,                 10).
-define(S2LOOPMETHODS_DEPTH,                    11).
-define(S2LOOPMETHODS_IS_HOLE,                  12).
-define(S2LOOPMETHODS_SIGN,                     13).
-define(S2LOOPMETHODS_NUM_VERTICES,             14).
-define(S2LOOPMETHODS_VERTEX,                   15).
-define(S2LOOPMETHODS_IS_NORMALIZED,            16).
-define(S2LOOPMETHODS_NORMALIZE,                17).
-define(S2LOOPMETHODS_INVERT,                   18).
-define(S2LOOPMETHODS_GET_AREA,                 19).
-define(S2LOOPMETHODS_GET_CENTROID,             20).
-define(S2LOOPMETHODS_GET_TURNING_ANGLE,        21).
-define(S2LOOPMETHODS_CONTAINS,                 22).
-define(S2LOOPMETHODS_INTERSECTS,               23).
-define(S2LOOPMETHODS_CONTAINS_NESTED,          24).
-define(S2LOOPMETHODS_CONTAINS_OR_CROSSES,      25).
-define(S2LOOPMETHODS_BOUNDARY_EQUALS,          26).
-define(S2LOOPMETHODS_BOUNDARY_APPROX_EQUALS,   27).
-define(S2LOOPMETHODS_BOUNDARY_NEAR,            28).

-define(S2LOOPMETHODS_GET_RECT_BOUND,           29).

-define(S2LOOPMETHODS_CONTAINS_S2CELLID,        30).
-define(S2LOOPMETHODS_MAY_INTERSECT_S2CELLID,   31).
-define(S2LOOPMETHODS_CONTAINS_S2POINT,         32).
-define(S2LOOPMETHODS_ENCODE,                   33).

